on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v2
              with:
                  distribution: "zulu"
                  java-version: "11"
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  cache: true
                  cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
                  cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
            - run: flutter pub get
            - run: flutter test
            - run: flutter build apk
            - run: flutter build appbundle
